<a href="https://colab.research.google.com/github/BenxiaHu/DeepLearning/blob/main/pytorch_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# linear regression


Dependencies:
* torch: 0.1.11
* matplotlib

In [18]:
import torch
import math
torch.manual_seed(1)
dtype = torch.float
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#device = torch.device('cpu')

class LinearRegression(torch.nn.Module):
    def __init__(self):
      super().__init__()
      self.a = torch.nn.Parameter(torch.randn((),device=device))
      self.b = torch.nn.Parameter(torch.randn((),device=device))
      self.c = torch.nn.Parameter(torch.randn((),device=device))
      self.d = torch.nn.Parameter(torch.randn((),device=device))
      # self.linear = torch.nn.Linear(1,1)

    def forward(self, x1,x2,x3):
      # out = self.linear(x)
      # return out
      print(x1)
      return self.a + self.b * x1 + self.c * x2 + self.d * x3

    def string(self):
      return f'y = {self.a.item()} + {self.b.item()} x1 + {self.c.item()} x2 + {self.d.item()} x3'

  
x1 = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
x2 = torch.linspace(0, math.pi, 2000, device=device, dtype=dtype) + 2
x3 = torch.linspace(math.pi, 10,2000, device=device, dtype=dtype)
X = torch.stack((x1,x2,x3),-1)
print(X.shape)
print(X)
y = torch.linspace(10,100, 2000, device=device, dtype=dtype)
print(y.shape)
print(y)
# y = a*x1 + b*x2 + c*x3 + d
model = LinearRegression()
criterion = torch.nn.MSELoss(reduction='sum')
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

while True:
    # Forward pass: compute predicted y using operations on Tensors.
    y_pred = model(x1,x2,x3)
    # Compute and print loss using operations on Tensors.
    # Now loss is a Tensor of shape (1,)
    # loss.item() gets the scalar value held in the loss.
    loss = criterion(y_pred, y)
    # Zero the gradients before running the backward pass.
    if(loss.item() > 0.1):
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    else:
        break
print(y_pred)
print(loss.item())
# You can access the first layer of `model` like accessing the first item of a list
linear_layer = model[0]
print(linear_layer)
# For linear layer, its parameters are stored as `weight` and `bias`.
print(f'Result: y = {linear_layer.bias.item()} + {linear_layer.weight[:, 0].item()} x1 + {linear_layer.weight[:, 1].item()} x2 + {linear_layer.weight[:, 1].item()} x3')

print(linear_layer.weight)




Streaming output truncated to the last 5000 lines.
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])
tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3

KeyboardInterrupt: ignored